/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.InputMethodEvent;
import java.awt.event.InputMethodListener;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author niebz
 */
public class AdCheckHour extends javax.swing.JFrame {

    /**
     * Creates new form AdCheckHour
     */
    public AdCheckHour() {
        initComponents();
    }
    
String cur_id ;
    public AdCheckHour(String id) {
        initComponents();
        String [] column = {"ลำดับ","ปีการศึกษา","ประเภท","วันที่","จำนวนชั่วโมง"};
        DefaultTableModel md = new DefaultTableModel(column,0);
        tbHour.getTableHeader().setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); 
        tbHour.setModel(md);
        
        //Logout
        jTabbedPane1.addChangeListener( new ChangeListener() {
            @Override
            public void stateChanged (ChangeEvent e) {
                if (jTabbedPane1.getSelectedIndex()==2) {
                    dispose();
                    LoginPage lp = new LoginPage();
                    lp.setVisible(true);
                }
            }
        });


        //เช็คการเปลี่ยนแปลง ถ้ามีการเพิ่มข้อมูลจะเรียกใช้ Method 
        txtID.getDocument().addDocumentListener( new DocumentListener() {
            @Override
            public void insertUpdate (DocumentEvent e) {
                setname();
            }

            @Override
            public void removeUpdate (DocumentEvent e) {

            }

            @Override
            public void changedUpdate (DocumentEvent e) {
                setname();
            }
        } );

    }

    private void setname () {
        String user_id = txtID.getText();
        String sql = String.format("Select user_name,user_lastname from users where user_id = '%s'",user_id);
        DB db = new DB();
        try {
            ResultSet rs = db.getResultSet(sql);
            if (rs.next()) {
                txtName.setText(rs.getString(1));
                txtLastname.setText(rs.getString(2));
            }
        }
        catch (Exception ex) {

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHour = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtIDCheck = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHour = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtLastname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbxType = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        jDate = new com.github.lgooddatepicker.components.DatePicker();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("TH SarabunPSK", 0, 18)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setMinimumSize(new java.awt.Dimension(590, 380));
        jPanel1.setPreferredSize(new java.awt.Dimension(590, 380));

        tbHour.setFont(new java.awt.Font("TH SarabunPSK", 0, 18)); // NOI18N
        tbHour.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbHour);

        jLabel5.setFont(new java.awt.Font("TH Sarabun New", 0, 20)); // NOI18N
        jLabel5.setText("รหัสนักศึกษา");

        txtIDCheck.setFont(new java.awt.Font("TH Sarabun New", 0, 20)); // NOI18N
        txtIDCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDCheckActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N
        btnSearch.setText("ค้นหา");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N
        btnEdit.setText("แก้ไข");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N
        btnDelete.setText("ลบ");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel5)
                .addGap(40, 40, 40)
                .addComponent(txtIDCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnSearch)
                .addGap(18, 18, 18)
                .addComponent(btnEdit)
                .addGap(18, 18, 18)
                .addComponent(btnDelete))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5))
                    .addComponent(txtIDCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("ตรวจสอบ", jPanel1);

        btnSave.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        btnSave.setText("บันทึก");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtID.setFont(new java.awt.Font("TH Sarabun New", 0, 20)); // NOI18N
        txtID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIDFocusLost(evt);
            }
        });
        txtID.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtIDInputMethodTextChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("TH Sarabun New", 0, 20)); // NOI18N
        jLabel3.setText("จำนวนชั่วโมง");

        txtHour.setFont(new java.awt.Font("TH Sarabun New", 0, 20)); // NOI18N

        jLabel4.setFont(new java.awt.Font("TH Sarabun New", 0, 20)); // NOI18N
        jLabel4.setText("วันที่");

        jLabel1.setFont(new java.awt.Font("TH Sarabun New", 0, 20)); // NOI18N
        jLabel1.setText("รหัสนักศึกษา");

        txtName.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N
        txtName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtName.setFocusable(false);

        jLabel7.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N
        jLabel7.setText("ชื่อ");

        txtLastname.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N
        txtLastname.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtLastname.setFocusable(false);

        jLabel6.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N
        jLabel6.setText("นามสกุล");

        jLabel2.setFont(new java.awt.Font("TH SarabunPSK", 0, 18)); // NOI18N
        jLabel2.setText("* โปรดเพิ่มชั่วโมงทุนตามความเป็นจริง");

        jLabel8.setFont(new java.awt.Font("TH Sarabun New", 0, 20)); // NOI18N
        jLabel8.setText("ประเภทกิจกรรม");

        cbxType.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N
        cbxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "กรุณาเลือก", "ชั่วโมงส่วนกลาง", "ชั่วโมงคณะ", "ชั่วโมงนักศึกษาทุน" }));

        jLabel9.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N
        jLabel9.setText("ปีการศึกษา");

        txtYear.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N

        jDate.setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6)
                        .addGap(14, 14, 14)
                        .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel9)
                        .addGap(40, 40, 40)
                        .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(cbxType, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtHour, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(550, 550, 550)
                        .addComponent(btnSave)))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(cbxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnSave))
        );

        jTabbedPane1.addTab("เพิ่มชั่วโมงทุน", jPanel2);

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("ออกจากระบบ", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDCheckActionPerformed

  
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_btnSearchActionPerformed
  
    static ArrayList<Integer> keepid = new ArrayList<Integer>();
    protected static void search() {
        keepid.clear();
        DB db = new DB();
        try {
        String user_id = txtIDCheck.getText();
        String sql = String.format("select user_id from users where user_id='%s''",user_id);
        ResultSet rs = db.getResultSet(sql);
        
        String [] column = {"ลำดับ","ปีการศึกษา","ประเภท","วันที่","จำนวนชั่วโมง"};
            sql = String.format("Select year,sht.type_name,date,hour,hour_id from schorlarship_hour as sh  inner join schorlarship_type as sht on sh.type_id = sht.type_id  where user_id = '%s'",user_id);
            DefaultTableModel md = new DefaultTableModel(column,0);
            rs = db.getResultSet(sql);
            int i = 0;
            while(rs.next()) {
                i++;
                String [] row = {String.valueOf(i),rs.getString(1),rs.getString(2),rs.getString(3),
                rs.getString(4)};
                keepid.add(rs.getInt(5));
                md.addRow(row);
            }
            tbHour.getTableHeader().setFont(new java.awt.Font("TH SarabunPSK", 0, 20)); // NOI18N
            tbHour.setModel(md);
        }
        catch (Exception e) {
            
        }
    }
    
    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String user_id = txtID.getText();
        String type_name = cbxType.getSelectedItem().toString();
        String datepick = jDate.getDate()+"";
        int hour = Integer.parseInt(txtHour.getText());
        int year = Integer.parseInt(txtYear.getText());
        
        String sql = String.format("Insert into schorlarship_hour(user_id,type_id,hour,date,year) values('%s',(Select type_id from schorlarship_type where type_name = '%s'),'%d','%s','%d')",user_id,type_name,hour,datepick,year);
        //System.out.println(sql);
        DB temp = new DB();
        try {
            if (temp.execute(sql)) {
                txtID.setText("");
                txtName.setText("");
                txtLastname.setText("");
                txtYear.setText("");
                txtHour.setText("");
                cbxType.setSelectedIndex(0);
            }else JOptionPane.showMessageDialog(null, "Add Fail!");
        }
        catch (Exception e) {
            
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIDFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtIDFocusLost

    private void txtIDInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtIDInputMethodTextChanged
        // TODO add your handling code here:
        String user_id = txtID.getText();
        String sql = String.format("Select user_name,user_lastname from users where user_id = '%s'",user_id);
        DB db = new DB();
        try {
            ResultSet rs = db.getResultSet(sql);
            if (rs.next()) {
                txtName.setText(rs.getString(1));
                txtLastname.setText(rs.getString(2));
            }
        }
        catch (Exception e) {
            
        }
    }//GEN-LAST:event_txtIDInputMethodTextChanged

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
       delete ();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void delete (){
         String sql = String.format("Delete from schorlarship_hour where hour_id = '%d'",keepid.get(tbHour.getSelectedRow()));
        keepid.remove(tbHour.getSelectedRow());
        DB temp = new DB();
        //JOptionPane.showMessageDialog(null, sql);
        try {
            if (temp.execute(sql)) {
                JOptionPane.showMessageDialog(null, "Delete sucess!");
            }else JOptionPane.showMessageDialog(null, "Add Fail!");
        }
        catch (Exception e) {
            
        }
        search();
    }
    
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        EditPage ep = new EditPage(this,true, txtIDCheck.getText(),keepid.get(tbHour.getSelectedRow()));
        ep.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    public boolean isNumeric(String numeric){
        try {
            int num1 = Integer.parseInt(numeric);
            return true;
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please use Numeric");
            return false;
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdCheckHour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdCheckHour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdCheckHour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdCheckHour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdCheckHour().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbxType;
    private com.github.lgooddatepicker.components.DatePicker jDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private static javax.swing.JTable tbHour;
    private javax.swing.JTextField txtHour;
    private javax.swing.JTextField txtID;
    private static javax.swing.JTextField txtIDCheck;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
