/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
/**
 *
 * @author niebz
 */
public class UserCheckHour extends javax.swing.JFrame {

    /**
     * Creates new form UserCheckHour
     */
    public UserCheckHour() {
        initComponents();
    }
String cur_id ;
    public UserCheckHour(String id) {
        initComponents();
        cur_id = id;
        DB db = new DB();
        try {
            String sql = String.format("Select * from users where user_id = '%s'",cur_id);
            ResultSet rs = db.getResultSet(sql);
            if (rs.next()) {
                txtName.setText(rs.getString(1)+" "+rs.getString(2));
                txtID.setText(rs.getString(3));
                txtIDCheck.setText(rs.getString(3));
                txtDepart.setText(rs.getString(4));
                txtMajor.setText(rs.getString(5));
                txtYear.setText(rs.getString(6));
                txtTel.setText(rs.getString(7));
            }

            sql = String.format("Select sum(hour) from schorlarship_hour where user_id = '%s' ",cur_id);
            rs = db.getResultSet(sql); //เก็บผลรันแล้วดึงผลมาแสดง
            if (rs.next()) txtTotalHour.setText(rs.getString(1));
            
            String [] column = {"ลำดับ","ปีการศึกษา","ประเภท","วันที่","จำนวนชั่วโมง"};
            sql = String.format("Select year,type_id,date,hour from schorlarship_hour where user_id = '%s'",cur_id);
            DefaultTableModel md = new DefaultTableModel(column,0);
            rs = db.getResultSet(sql);
            int i = 0;

            while(rs.next()) {
                i++;
                String [] row = {String.valueOf(i),rs.getString(1),rs.getString(2),rs.getString(3),
                rs.getString(4)};

                md.addRow(row);
            }
            tbHour.getTableHeader().setFont(new java.awt.Font("FC Lamoon", 0, 20)); // NOI18N
            tbHour.setModel(md);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
        //Logout
        jTabbedPane1.addChangeListener( new ChangeListener() {

            @Override
            public void stateChanged (ChangeEvent e) {
                if (jTabbedPane1.getSelectedIndex()==2) {
                    dispose();
                    LoginPage lp = new LoginPage();
                    lp.setVisible(true);
                }
            }
        });
        search();
    }
    
    ArrayList<Integer> keepid = new ArrayList<Integer>();
    protected void search() {
        keepid.clear();
        DB db = new DB();
        try {
        String sql = String.format("select user_id from users where user_id='%s''",cur_id);
        ResultSet rs = db.getResultSet(sql);
        
        String [] column = {"ลำดับ","ปีการศึกษา","ประเภท","วันที่","จำนวนชั่วโมง"};
            sql = String.format("Select year,sht.type_name,date,hour,hour_id from schorlarship_hour as sh  inner join schorlarship_type as sht on sh.type_id = sht.type_id  where user_id = '%s'",cur_id);
            DefaultTableModel md = new DefaultTableModel(column,0);
            rs = db.getResultSet(sql);
            int i = 0;

            while(rs.next()) {
                i++;
                String [] row = {String.valueOf(i),rs.getString(1),rs.getString(2),rs.getString(3),
                rs.getString(4)};
                keepid.add(rs.getInt(5));
                md.addRow(row);
            }
            tbHour.getTableHeader().setFont(new java.awt.Font("FC Lamoon", 0, 20)); // NOI18N
            tbHour.setModel(md);
        }
        catch (Exception e) {
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();
        txtID = new javax.swing.JLabel();
        txtDepart = new javax.swing.JLabel();
        txtYear = new javax.swing.JLabel();
        txtMajor = new javax.swing.JLabel();
        txtTel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtIDCheck = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHour = new javax.swing.JTable();
        txtTotalHour = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("FC Lamoon", 0, 18)); // NOI18N

        jPanel2.setEnabled(false);
        jPanel2.setFocusable(false);
        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentMoved(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("FC Lamoon", 1, 24)); // NOI18N
        jLabel6.setText("ข้อมูลส่วนตัว");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 35, -1, -1));

        jLabel1.setFont(new java.awt.Font("FC Lamoon", 1, 20)); // NOI18N
        jLabel1.setText("ชื่อ - สกุล");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 100, 70, -1));

        jLabel2.setFont(new java.awt.Font("FC Lamoon", 1, 20)); // NOI18N
        jLabel2.setText("รหัสนักศึกษา");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 163, 79, -1));

        jLabel3.setFont(new java.awt.Font("FC Lamoon", 1, 20)); // NOI18N
        jLabel3.setText("คณะ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 228, 37, -1));

        jLabel4.setFont(new java.awt.Font("FC Lamoon", 1, 20)); // NOI18N
        jLabel4.setText("สาขา");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("FC Lamoon", 1, 20)); // NOI18N
        jLabel7.setText("ชั้นปี");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 298, 37, -1));

        jLabel9.setFont(new java.awt.Font("FC Lamoon", 1, 20)); // NOI18N
        jLabel9.setText("เบอร์ติดต่อ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        txtName.setFont(new java.awt.Font("FC Lamoon", 0, 20)); // NOI18N
        txtName.setText("--");
        jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 100, -1, -1));

        txtID.setFont(new java.awt.Font("FC Lamoon", 0, 20)); // NOI18N
        txtID.setText("--");
        jPanel2.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 163, -1, -1));

        txtDepart.setFont(new java.awt.Font("FC Lamoon", 0, 20)); // NOI18N
        txtDepart.setText("--");
        jPanel2.add(txtDepart, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 228, -1, -1));

        txtYear.setFont(new java.awt.Font("FC Lamoon", 0, 20)); // NOI18N
        txtYear.setText("--");
        jPanel2.add(txtYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 298, -1, -1));

        txtMajor.setFont(new java.awt.Font("FC Lamoon", 0, 20)); // NOI18N
        txtMajor.setText("--");
        jPanel2.add(txtMajor, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        txtTel.setFont(new java.awt.Font("FC Lamoon", 0, 20)); // NOI18N
        txtTel.setText("--");
        jPanel2.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        jTabbedPane1.addTab("ส่วนตัว", jPanel2);

        jLabel5.setFont(new java.awt.Font("FC Lamoon", 0, 20)); // NOI18N
        jLabel5.setText("รหัสนักศึกษา");

        txtIDCheck.setFont(new java.awt.Font("FC Lamoon", 0, 20)); // NOI18N
        txtIDCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDCheckActionPerformed(evt);
            }
        });

        tbHour.setFont(new java.awt.Font("TH SarabunPSK", 0, 18)); // NOI18N
        tbHour.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbHour.setFocusable(false);
        jScrollPane1.setViewportView(tbHour);

        txtTotalHour.setFont(new java.awt.Font("FC Lamoon", 0, 20)); // NOI18N
        txtTotalHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalHourActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("FC Lamoon", 0, 20)); // NOI18N
        jLabel8.setText("รวม");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(27, 27, 27)
                        .addComponent(txtIDCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel8)
                        .addGap(26, 26, 26)
                        .addComponent(txtTotalHour, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtIDCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8)
                    .addComponent(txtTotalHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jTabbedPane1.addTab("ตรวจสอบ", jPanel1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("ออกจากระบบ", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDCheckActionPerformed

    private void txtTotalHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalHourActionPerformed

    private void jPanel2ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2ComponentMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserCheckHour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserCheckHour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserCheckHour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserCheckHour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserCheckHour().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbHour;
    private javax.swing.JLabel txtDepart;
    private javax.swing.JLabel txtID;
    private javax.swing.JTextField txtIDCheck;
    private javax.swing.JLabel txtMajor;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtTel;
    private javax.swing.JTextField txtTotalHour;
    private javax.swing.JLabel txtYear;
    // End of variables declaration//GEN-END:variables
}
